### ISSUE TITLE
LOTRBanner crash

### ISSUE THREAD

**Issue by EpicNose** [Hummel009/The-Lord-of-the-Rings#2]
server crash and client crash when a banner in hand or there is a chunk loading within banner.

[latest.log](https://github.com/Hummel009/The-Lord-of-the-Rings/files/9860042/latest.log)

![image](https://user-images.githubusercontent.com/87713662/197768555-8883627f-8434-4246-813e-7ef3762458dd.png)

i make this change and it works now... I don't know if it is correct
![image](https://user-images.githubusercontent.com/87713662/197768885-4aa686b9-b742-482b-9bd9-7820a9f7c017.png)

**Comment by Hummel009** [comment]
Yes, that's correct. Sorry for the long answer, I didn't get ping from this issue.
