### ISSUE TITLE
the north-south gate is out of order

### ISSUE THREAD

**Issue by EpicNose** [Hummel009/The-Lord-of-the-Rings#3]
![image](https://user-images.githubusercontent.com/87713662/210590896-0081181c-c4cb-4439-bdd2-37af90c0715d.png)
The north-south gate is out of order, but the east-west gate is normal
and the powered way to open the gate is normal
![image](https://user-images.githubusercontent.com/87713662/210627852-2dff0bb4-2af9-46cf-8135-e9fd8bc509d8.png)

**Comment by Hummel009** [comment]
Hi! I can't repeat this bug for me. Redstone and usual ways work as usual. Also I checked the original LOTR with different decompilators and get the same code without any error or ambiguity. 
![Снимок экрана (54)](https://user-images.githubusercontent.com/60618853/211149610-dbde756e-d26b-44ac-9713-e8ed60eea401.png)

**Comment by EpicNose** [comment]
Maybe you can try this problem in the server . I found this problem in my test cauldron server and i can't solve this problem till now. There is no problem in the singleplayer mode. 
Thank you for your efforts！
