### ISSUE TITLE
You should really try turning this into a 1.12 mod with different code.

### ISSUE THREAD

**Issue by MagmaBro123** [Hummel009/The-Lord-of-the-Rings#4]
Title.

The LOTR mod is a great mod, but they skipped 1.12 completely, and this mod would be amazing on a version that has many other great mods. (I do know that this mod's community can be... quite toxic about anyone messing with its code, hence the title. Ik it'd be a lot of work, but you know LOTR quite well I think, so it might not be that hard I hope.)

**Comment by Hummel009** [comment]
I know one russian team that is working on LOTR 1.12.2 right now. They are "LOTR Reworked" team. You can contact them in their discord to ask something about development. https://discord.gg/PNterQvW

I fully support your opinion that the mod on version 1.12 is a great idea. The team I mentioned above has been doing this work for about a year and is close to the final (according to them, several tens of thousands of errors have been fixed, and there are several thousand left. Perhaps 90% is already ready).

**Comment by MagmaBro123** [comment]
Oh, neat. Meavens has been who knows where for quite a while, so I'm surprised they're doing something with the mod, though I doubt their version is open-source.

**Comment by Hummel009** [comment]
Ugh, I have no idea how to make a trading editor... not even an idea how to put it in json. I still do not have such a high level in programming, I'm just a student.

And as for the LOTR Reworked team, yes, I think their project won't be open-source. Although no one prevents decompiling and deobfuscating this source code. Exactly the same as it was with LOTR 1.7.10 and as I did with LOTR 1.16.5. Another thing is that then we need a long period of testing and catching errors.

**Comment by MagmaBro123** [comment]
> Ugh, I have no idea how to make a trading editor... not even an idea how to put it in json. I still do not have such a high level in programming, I'm just a student.
> 
> And as for the LOTR Reworked team, yes, I think their project won't be open-source. Although no one prevents decompiling and deobfuscating this source code. Exactly the same as it was with LOTR 1.7.10 and as I did with LOTR 1.16.5. Another thing is that then we need a long period of testing and catching errors.

Ah, sorry then. Just wish their textures were a bit better, and they don't allow servers for whatever reason.

**Comment by Hummel009** [comment]
You know, competition. They compete with other servers.

**Comment by MagmaBro123** [comment]
Ah.
